### ISSUE TITLE
Trustbadge buyer protection requires `unsafe-eval` CSP directive

### ISSUE THREAD

**Issue by depoulo** [trustedshops/trustbadge#1]
First of all, this is probably not 100% the right place, since the trustbadge JS code itself is closed source. Anyway, here we go:

On my shop system's order confirmation page, the JS console tells it just blocked some code execution when my server is configured to send a Content Security Policy header that limits the allowed `script-src`es.

The blocked code looks like this, and IMHO won't make much more sense if you'd rewrite it to using `JSON.parse` instead. But it would at least not require us to set the `unsafe-eval` directive:

```js
XHR.onload = function() {
  if (XHR.readyState == 4) {
    response = eval("(" + XHR.responseText + ")");
    callBack(response);
  } else {
    var response = eval("(" + XHR.responseText + ")");
    callBack(response);
  }
}
```

**Comment by tolzhabayev** [comment]
Hey,

thank you for your feedback we will look into this issue and will keep you updated about the status.

**Comment by tolzhabayev** [comment]
Hey again,

we have removed the eval function from the trustbadge code, thank you for your feedback!

**Comment by depoulo** [comment]
👍
